/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpage;
import CONFIG.DBCONNECTOR;
import com.toedter.calendar.DateUtil;
import com.sun.javafx.collections.IntegerArraySyncer;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.text.*; 
import java.awt.print.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
public class userview extends javax.swing.JInternalFrame {
private Connection con;
DefaultTableModel model;
    /**
     * Creates new form dashabord
     */
    public userview() {
        initComponents();
        viewdetails();

          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
    }
     public void search(String str){
    model = (DefaultTableModel) RECORDS.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    RECORDS.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    }
  public void viewdetails(){
        try {
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cemeterymapping", "root", "");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT registered_deceased.RECORD_ID, registered_deceased.NAME, registered_deceased.LASTNAME, registered_deceased.BORN_DATE, registered_deceased.DEATH_DATE, grave.SECTION_NO\n" +
"FROM registered_deceased, grave\n" +
"WHERE registered_deceased.GRAVE_ID = grave.GRAVE_ID\n" +
"ORDER BY registered_deceased.RECORD_ID");
             
             while(rs.next()){
               String id = rs.getString("RECORD_ID");
             String isbn = rs.getString("NAME");
             String studentid = rs.getString("LASTNAME");
             String issuedate = rs.getString("BORN_DATE");
             String duedate = rs.getString("DEATH_DATE");
             String status = rs.getString("SECTION_NO");
             
             Object [] obj = {id,isbn,studentid,issuedate,duedate,status};
             model = (DefaultTableModel) RECORDS.getModel();
             model.addRow(obj);
             
             }
             
             
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    
    }
    public void cleartable(){
    DefaultTableModel model =(DefaultTableModel)RECORDS.getModel();
    model.setRowCount(0);
     
    
    
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RECORDS = new rojeru_san.complementos.RSTableMetro();
        jLabel16 = new javax.swing.JLabel();
        VIEWALL = new necesario.RSMaterialButtonCircle();
        search = new app.bolivia.swing.JCTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 58, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RECORDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RECORD ID", "NAME", "LASTNAME", "BORN DATE", "DEATH DATE", "LOCATION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RECORDS.setColorBackgoundHead(new java.awt.Color(153, 153, 153));
        RECORDS.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        RECORDS.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        RECORDS.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        RECORDS.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        RECORDS.setFuenteFilas(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        RECORDS.setFuenteFilasSelect(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        RECORDS.setFuenteHead(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        RECORDS.setGridColor(new java.awt.Color(204, 204, 204));
        RECORDS.setGrosorBordeFilas(0);
        jScrollPane1.setViewportView(RECORDS);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 390));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 870, 390));

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("VIEW DECEASED");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 320, 80));

        VIEWALL.setBackground(new java.awt.Color(0, 102, 102));
        VIEWALL.setText("VIEW ALL");
        VIEWALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWALLActionPerformed(evt);
            }
        });
        jPanel1.add(VIEWALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 130, 40));

        search.setBorder(null);
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        search.setPlaceholder("SEARCH");
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 650, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VIEWALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWALLActionPerformed
         cleartable();
     viewdetails();
    }//GEN-LAST:event_VIEWALLActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String seachst = search.getText();
        search(seachst);
    }//GEN-LAST:event_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro RECORDS;
    private necesario.RSMaterialButtonCircle VIEWALL;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private app.bolivia.swing.JCTextField search;
    // End of variables declaration//GEN-END:variables
}
