/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cemetery;
import java.awt.Color;
import internalpage.*;
import internalpage.dashabord;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
/**
 *
 * @author User
 */
public class userdashboard extends javax.swing.JFrame {

    /**
     * Creates new form DASHBOARD
     */
    public userdashboard() {
        initComponents();
    }
  Color navcolor = new Color(178,34,34);
    Color headcolor = new Color(153,153,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DI = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        VL = new javax.swing.JPanel();
        LO = new javax.swing.JPanel();
        LOGIN = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("bg.png"));
        Image img=icon.getImage();
        maindesk = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(img,0,0,getWidth(),getHeight(),this);

            }

        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 34, 34));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AB.setBackground(new java.awt.Color(178, 34, 34));
        AB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ABMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ABMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ABMouseExited(evt);
            }
        });
        AB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MAP");
        AB.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 102, -1));

        jPanel1.add(AB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, -1));

        DI.setBackground(new java.awt.Color(178, 34, 34));
        DI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DIMouseExited(evt);
            }
        });
        DI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DECEASED INFO");
        DI.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 150, -1));

        jPanel1.add(DI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 190, 40));

        VL.setBackground(new java.awt.Color(178, 34, 34));
        VL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VLMouseExited(evt);
            }
        });
        VL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(VL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 469, 190, -1));

        LO.setBackground(new java.awt.Color(178, 34, 34));
        LO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOMouseExited(evt);
            }
        });
        LO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGIN.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        LOGIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGIN.setText("ADMIN LOGIN");
        LO.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 170, -1));

        jPanel1.add(LO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 540));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close (2).png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 40));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize-sign (2).png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setText("CEMETERY MAPPING SYSTEM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 620, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1060, 50));

        javax.swing.GroupLayout maindeskLayout = new javax.swing.GroupLayout(maindesk);
        maindesk.setLayout(maindeskLayout);
        maindeskLayout.setHorizontalGroup(
            maindeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        maindeskLayout.setVerticalGroup(
            maindeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(maindesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 865, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(headcolor);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(navcolor);
    }//GEN-LAST:event_exitMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void ABMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABMouseEntered
       AB.setBackground(headcolor);
    }//GEN-LAST:event_ABMouseEntered

    private void ABMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABMouseExited
         AB.setBackground(navcolor);
    }//GEN-LAST:event_ABMouseExited

    private void DIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIMouseEntered
        DI.setBackground(headcolor);
    }//GEN-LAST:event_DIMouseEntered

    private void DIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIMouseExited
       DI.setBackground(navcolor);
    }//GEN-LAST:event_DIMouseExited

    private void VLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VLMouseEntered
       VL.setBackground(headcolor);
    }//GEN-LAST:event_VLMouseEntered

    private void VLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VLMouseExited
     VL.setBackground(navcolor);
    }//GEN-LAST:event_VLMouseExited

    private void LOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOMouseEntered
        LO.setBackground(headcolor);
    }//GEN-LAST:event_LOMouseEntered

    private void LOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOMouseExited
       LO.setBackground(navcolor);
    }//GEN-LAST:event_LOMouseExited

    private void ABMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABMouseClicked
      maindesk.removeAll();
        map ab=new map();
        maindesk.add(ab).setVisible(true);
    }//GEN-LAST:event_ABMouseClicked

    private void DIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIMouseClicked
           maindesk.removeAll();
        userview as =new userview();
        maindesk.add(as).setVisible(true); 
    }//GEN-LAST:event_DIMouseClicked

    private void LOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOMouseClicked
         int a = JOptionPane.showConfirmDialog(null,"Do You Want To Login As Admin?");
        if(a == JOptionPane.YES_OPTION){
            login in = new login ();
            in.setVisible(true);
            this.dispose();}
    }//GEN-LAST:event_LOMouseClicked

    private void VLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VLMouseClicked

    }//GEN-LAST:event_VLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AB;
    private javax.swing.JPanel DI;
    private javax.swing.JPanel LO;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JPanel VL;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JDesktopPane maindesk;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
